[package]
name = "rust_kafka_producer_consumer"
version = "0.1.0"
authors = ["joao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdkafka = "0.23.1"